language: node.js

node_js:
  - node

before_script:
  - yarn global add gatsby-cli

install:
  - yarn install

script:
  - yarn run build

deploy:
  provider: pages
  local_dir: public
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master

sudo: false # route your build to the container-based infrastructure for a faster build

cache: npm # caching packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
